export const MockIDRXAbi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "FAUCET_AMOUNT",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FAUCET_COOLDOWN",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "faucet",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lastFaucetClaim",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "simulatedTopUp",
    inputs: [
      { name: "user", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "TopUpCompleted",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "FaucetClaimed",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { indexed: true, name: "from", type: "address" },
      { indexed: true, name: "to", type: "address" },
      { indexed: false, name: "value", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { indexed: true, name: "owner", type: "address" },
      { indexed: true, name: "spender", type: "address" },
      { indexed: false, name: "value", type: "uint256" },
    ],
  },
] as const;

export const ArisanFactoryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_token", type: "address" },
      { name: "_debtNFT", type: "address" },
      { name: "_reputationRegistry", type: "address" },
      { name: "_platformWallet", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createPool",
    inputs: [
      { name: "contributionAmount", type: "uint256" },
      { name: "securityDepositAmount", type: "uint256" },
      { name: "maxMembers", type: "uint256" },
      { name: "paymentDay", type: "uint8" },
      { name: "vouchRequired", type: "bool" },
      { name: "rotationPeriod", type: "uint8" },
      { name: "poolName", type: "string" },
      { name: "category", type: "string" },
    ],
    outputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPool",
    inputs: [{ name: "poolId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserPools",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAdminPools",
    inputs: [{ name: "admin", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pools",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "debtNFT",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reputationRegistry",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "platformWallet",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PoolCreated",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "poolAddress", type: "address" },
      { indexed: true, name: "admin", type: "address" },
      { indexed: false, name: "contributionAmount", type: "uint256" },
      { indexed: false, name: "securityDeposit", type: "uint256" },
      { indexed: false, name: "maxMembers", type: "uint256" },
      { indexed: false, name: "paymentDay", type: "uint8" },
      { indexed: false, name: "vouchRequired", type: "bool" },
      { indexed: false, name: "rotationPeriod", type: "uint8" },
      { indexed: false, name: "poolName", type: "string" },
      { indexed: false, name: "category", type: "string" },
    ],
  },
  {
    type: "event",
    name: "PlatformWalletUpdated",
    inputs: [
      { indexed: true, name: "oldWallet", type: "address" },
      { indexed: true, name: "newWallet", type: "address" },
    ],
  },
] as const;

export const ArisanPoolAbi = [
  {
    type: "function",
    name: "poolId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "status",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentRound",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalRounds",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activatedAt",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundStartedAt",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recoveredFunds",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "GRACE_PERIOD",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PLATFORM_FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "config",
    inputs: [],
    outputs: [
      { name: "contributionAmount", type: "uint256" },
      { name: "securityDepositAmount", type: "uint256" },
      { name: "maxMembers", type: "uint256" },
      { name: "paymentDay", type: "uint8" },
      { name: "vouchRequired", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPoolConfig",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "contributionAmount", type: "uint256" },
          { name: "securityDepositAmount", type: "uint256" },
          { name: "maxMembers", type: "uint256" },
          { name: "paymentDay", type: "uint8" },
          { name: "vouchRequired", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPoolStatus",
    inputs: [],
    outputs: [
      { name: "_status", type: "uint8" },
      { name: "_currentRound", type: "uint256" },
      { name: "_totalRounds", type: "uint256" },
      { name: "_activeMembers", type: "uint256" },
      { name: "_deadline", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMemberList",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPendingList",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRotationOrder",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMemberInfo",
    inputs: [{ name: "member", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "status", type: "uint8" },
          { name: "lockedStake", type: "uint256" },
          { name: "liquidBalance", type: "uint256" },
          { name: "joinedAt", type: "uint256" },
          { name: "hasClaimedPayout", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVouchesReceived",
    inputs: [{ name: "member", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "voucher", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "returned", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasContributed",
    inputs: [
      { name: "round", type: "uint256" },
      { name: "member", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundWinners",
    inputs: [{ name: "round", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundPayouts",
    inputs: [{ name: "round", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundCompleted",
    inputs: [{ name: "round", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestJoin",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approveMember",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rejectMember",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeMember",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lockSecurityDeposit",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRotationOrder",
    inputs: [{ name: "order", type: "address[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "activatePool",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelPool",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "contribute",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vouch",
    inputs: [
      { name: "vouchee", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawVouch",
    inputs: [{ name: "vouchee", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reportDefault",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "determineWinner",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimPayout",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawLiquidFunds",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawSecurityDeposit",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "MemberRequested",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
    ],
  },
  {
    type: "event",
    name: "MemberApproved",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
    ],
  },
  {
    type: "event",
    name: "MemberRemoved",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
    ],
  },
  {
    type: "event",
    name: "SecurityDepositLocked",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ContributionMade",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "round", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "MemberVouched",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "voucher", type: "address" },
      { indexed: true, name: "vouchee", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "VouchReturned",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "voucher", type: "address" },
      { indexed: true, name: "vouchee", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "MemberReportedDefault",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
      { indexed: true, name: "reportedBy", type: "address" },
    ],
  },
  {
    type: "event",
    name: "DefaultResolved",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
      { indexed: false, name: "recoveredAmount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "WinnerDetermined",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "round", type: "uint256" },
      { indexed: true, name: "winner", type: "address" },
    ],
  },
  {
    type: "event",
    name: "PayoutClaimed",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "winner", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "platformFee", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PoolActivated",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: false, name: "totalRounds", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PoolCompleted",
    inputs: [{ indexed: true, name: "poolId", type: "uint256" }],
  },
  {
    type: "event",
    name: "PoolCancelled",
    inputs: [{ indexed: true, name: "poolId", type: "uint256" }],
  },
  {
    type: "event",
    name: "RotationOrderSet",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: false, name: "order", type: "address[]" },
    ],
  },
  {
    type: "event",
    name: "RoundStarted",
    inputs: [
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: true, name: "round", type: "uint256" },
      { indexed: false, name: "deadline", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "FundsWithdrawn",
    inputs: [
      { indexed: true, name: "member", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "withdrawType", type: "string" },
    ],
  },
] as const;

export const DebtNFTAbi = [
  {
    type: "function",
    name: "debtRecords",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "poolId", type: "uint256" },
      { name: "defaultedAmount", type: "uint256" },
      { name: "timestamp", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserDebtCount",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserDebtTokens",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasDebt",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenURI",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "DebtNFTMinted",
    inputs: [
      { indexed: true, name: "member", type: "address" },
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: true, name: "poolId", type: "uint256" },
      { indexed: false, name: "defaultedAmount", type: "uint256" },
    ],
  },
] as const;

export const ReputationRegistryAbi = [
  {
    type: "function",
    name: "getCompletedPools",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDefaultCount",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getReputation",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "completedPools", type: "uint256" },
          { name: "defaultCount", type: "uint256" },
          { name: "lastUpdated", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getReputationScore",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "int256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "canVouch",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PoolCompletionRecorded",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "totalCompleted", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "DefaultRecorded",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "totalDefaults", type: "uint256" },
    ],
  },
] as const;
